In [6]:
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from IPython.display import Image
from imutils import paths
import numpy as np
import cv2
import os
from sklearn.metrics import f1_score

In [9]:
def extract_histogram(image, bins = (8, 8, 8)):
    hist = cv2.calcHist([image], [0, 1, 2], None, bins, [0, 256, 0, 256, 0, 256])
    cv2.normalize(hist, hist)
    return hist.flatten()
imagePaths = sorted(list(paths.list_images("train")))
data = []
labels = []
for (i, imagePath) in enumerate(imagePaths):
    image = cv2.imread(imagePath, 1)
    label = imagePath.split(os.path.sep)[-1].split(".")[0]
    hist = extract_histogram(image)
    data.append(hist)
    labels.append(label)
le = LabelEncoder()
labels = le.fit_transform(labels)
(trainData, testData, trainLabels, testLabels) = train_test_split(np.array(data), labels, test_size = 0.25, random_state = 5) #random_state поменять на свой
model = LinearSVC(random_state = 5, C = 0.72) #random_state и C поменять на свои
model.fit(trainData, trainLabels)
predictions = model.predict(testData)

In [32]:
print(classification_report(testLabels, predictions, target_names = le.classes_)) 
#отсюда ответ в строчке macro avg, столбике f1-score (это задание, где нужно вывети среднее значение F1)
predictions = model.predict(testData)
round(f1_score(testLabels, predictions, average = 'macro'), 2)

precision    recall  f1-score   support

         cat       0.51      0.70      0.59       115
         dog       0.63      0.44      0.52       135

    accuracy                           0.56       250
   macro avg       0.57      0.57      0.55       250
weighted avg       0.57      0.56      0.55       250



0.55

In [15]:
model.coef_[0][448] #[0][x] x поменять на свой psi

0.0

In [18]:
round(model.coef_[0][241], 2) #[0][x] x поменять на свой psi

0.0

In [31]:
round(model.coef_[0][75], 2) #[0][x] x поменять на свой psi

0.36

В ответах далее:

    `array([0])` - ответ 0
    `array([1])` - ответ 1

In [24]:
singleImage = cv2.imread('test/cat.1046.jpg') # имя первой картинки
histt = extract_histogram(singleImage)
histt2 = histt.reshape(1, -1)
prediction = model.predict(histt2)
prediction

array([1], dtype=int64)

In [27]:
singleImage = cv2.imread('test/dog.1016.jpg') # имя второй картинки
histt = extract_histogram(singleImage)
histt2 = histt.reshape(1, -1)
prediction = model.predict(histt2)
prediction

array([0], dtype=int64)

In [29]:
singleImage = cv2.imread('test/cat.1028.jpg') # имя третьей картинки
histt = extract_histogram(singleImage)
histt2 = histt.reshape(1, -1)
prediction = model.predict(histt2)
prediction

array([0], dtype=int64)

In [30]:
singleImage = cv2.imread('test/cat.1032.jpg') # имя четвертой картинки
histt = extract_histogram(singleImage) 
histt2 = histt.reshape(1, -1)
prediction = model.predict(histt2)
prediction

array([0], dtype=int64)