# Машинное обучение и анализ данных

## Высшая Школа Цифровой Культуры

## Библиотека $\mathsf{NumPy}$

Подключение основных возможностей библиотеки $\mathsf{NumPy}$ осуществляется следующей строкой: 

In [1]:
import numpy as np

In [2]:
list1 = [1, -3, 2, 7] #Cписок
arr1 = np.array(list1) #Преобразование списка в ndarray
print(arr1) #Вывод массива
print(type(arr1)) #Вывод типа объекта

[ 1 -3  2  7]
<class 'numpy.ndarray'>


In [3]:
list2 = [[1, 2, 3, 4], [5, 6, 7, 8]] #Список из списков одинаковой длины
arr2 = np.array(list2) #Создание двумерного ndarray на основе list2
print(arr2) #Вывод массива
print(arr2.shape) #Вывод размерности массива

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [4]:
print(np.zeros(5)) #Массив размера (5, ) из пяти нулей
print(np.arange(30, 100, 9)) #Массив размера (9, ) из чисел от 30 до 100 с шагом в 9

[0. 0. 0. 0. 0.]
[30 39 48 57 66 75 84 93]


In [5]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr2 * 5)

[[ 5 10 15 20]
 [25 30 35 40]]


In [6]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(1 / arr2)

[[1.         0.5        0.33333333 0.25      ]
 [0.2        0.16666667 0.14285714 0.125     ]]


In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7]) #Одномерный массив
print(arr[5]) #Вывод элемента с индексом 5
print(arr[:3]) #Вывод элементов с индексами 0,1, и 2
print(arr[5:]) #Вывод всех элементов, индекс которых больше либо равен пяти
print(arr[2:4]) #Вывод элементов с индексам 2 и 3 

5
[0 1 2]
[5 6 7]
[2 3]


In [8]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr_slice = arr[3:6] #Выделение подмножества
arr_slice[:] = 13 #Присвоение всем элементам arr_slice значения 13
print(arr_slice)
print(arr)

[13 13 13]
[ 0  1  2 13 13 13  6  7]


In [9]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr_slice = arr[3:6].copy()
arr_slice[:] = 13 #Присвоение всем элементам arr_slice значения 13
print(arr_slice)
print(arr)

[13 13 13]
[0 1 2 3 4 5 6 7]


In [10]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[0]) # Вывод нулевого элемента (вывод массива)
print(arr2d[1][2]) # Вывод отдельного элемента

[1 2 3]
6


In [11]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d) #Выведем для удобства весь массив
print('Выделение подмножества')
print(arr2d[:2, 1:])  #Сначала выбираются строки с индексам меньше двух (нулевая и первая), затем столбцы с индексами больше, либо равными единице

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Выделение подмножества
[[2 3]
 [5 6]]


In [12]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Двумерный массив')
print(arr2d[:,2:])
print('Одномерный массив')
print(arr2d[:,2])

Двумерный массив
[[3]
 [6]
 [9]]
Одномерный массив
[3 6 9]


In [13]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Исходный массив')
print(arr2d)
print('Выбор элементов')
print(arr2d[[0, 1, 2], [1, 2, 0]])

Исходный массив
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Выбор элементов
[2 6 7]


In [14]:
arr = np.arange(15) #Создание одномерного массива из 15 элементов
print('Исходный массив')
print(arr)
print('Преобразование одномерного массива в двумерный размера (3, 5)')
arr = arr.reshape(3, 5)
print(arr) 
print('Транспонирование')
print(np.transpose(arr))
print('Обратно в одномерный массив')
print(arr.reshape(15,))

Исходный массив
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Преобразование одномерного массива в двумерный размера (3, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Транспонирование
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
Обратно в одномерный массив
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
X = np.arange(6).reshape(2, 3) #X — матрица размерности [2 x 3]
print(np.dot(X, X.T)) #Матричное умножение

[[ 5 14]
 [14 50]]


In [17]:
arr = np.arange(8).reshape(2, 4) #Создание массива размера (2, 4)
print('Исходный массив')
print(arr)
print('Извлечение корня')
print(np.sqrt(arr))
print('Нахождение синуса')
print(np.sin(arr))

Исходный массив
[[0 1 2 3]
 [4 5 6 7]]
Извлечение корня
[[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]]
Нахождение синуса
[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]]


С полным перечнем универсальных функций можно ознакомиться в документации https://numpy.org/doc/

### Выборочные характеристики

In [18]:
arr = np.arange(8) #Создание массива из 8 элементов
print('Исходный массив')
print(arr)
print('Среднее:', np.mean(arr))
print('Сумма:', np.sum(arr))

Исходный массив
[0 1 2 3 4 5 6 7]
Среднее: 3.5
Сумма: 28


In [19]:
arr = np.arange(8).reshape(2,4) #Создание массива 
print(arr) 
print(arr.mean(axis = 0)) #Средние значения по столбцами
print(arr.mean(axis = 1)) #Средние значения по строкам

[[0 1 2 3]
 [4 5 6 7]]
[2. 3. 4. 5.]
[1.5 5.5]


In [20]:
arr = np.array([[2, 0, 3], [4, 1, 7], [6, 8, 5]]) #Создание массива 
arr2 = arr.reshape(9,) #Одномерный массив на основее arr
print('Отсортированный двумерный массив')
print(np.sort(arr))
print('Отсортированный одномерный массив')
print(np.sort(arr2))

Отсортированный двумерный массив
[[0 2 3]
 [1 4 7]
 [5 6 8]]
Отсортированный одномерный массив
[0 1 2 3 4 5 6 7 8]
